FROM dalekurt/scala

MAINTAINER Dale-Kurt Murray "dalekurt.murray@gmail.com"

#VOLUME /opt/app

#WORKDIR /opt/app

# Compile with maven
CMD /usr/bin/mvn install

#ENTRYPOINT [/opt/app/mystuff-play-scala-webapp]

#CMD /usr/local/bin/sbt run

CMD ["/bin/bash"]
