FROM dalekurt/scala
MAINTAINER Dale-Kurt Murray "dalekurt.murray@gmail.com"

RUN mkdir /app

WORKDIR /app
ADD ./code /app
RUN mvn install

WORKDIR /app/mystuff-play-scala-webapp
RUN sbt run

EXPOSE 9000
